repos:
-   repo: local
    hooks:
    -   id: commit-msg-check
        name: 'Commit message check'
        entry: '.github/hooks/commit-msg-check.sh'
        language: script
        stages: [commit-msg]

