[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "semver"
version = "1.1.4"
update_changelog_on_bump = true
branch = "master"
commit = "48c89c5db49ddfa8881abef2f1c406582e9db268"
