[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "semver"
version = "1.1.5"
update_changelog_on_bump = true
branch = "master"
commit = "56e8a0c142b2c5fd4a99b649a0a86e9ef07c14b6"
