[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "semver"
version = "1.1.1"
update_changelog_on_bump = true
branch = "master"
commit = "7502e9629bca4c0c8ad19796a6979e05ed385530"
