[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$major.$minor.$patch$prerelease"
version_scheme = "semver"
major = 1
minor = 1
patch = 9
path = "pyproject.toml"
prerelease = "rc"
devrelease = "dev1"
update_changelog_on_bump = true
