[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "semver"
version = "1.1.4"
update_changelog_on_bump = true
branch = "master"
commit = "6f6563122314deefb8bd052b773a8f9199eb4d09"
