[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "semver"
version = "1.1.2"
update_changelog_on_bump = true
branch = "master"
commit = "c721edac41d9f91187fe0b47dccff1aab56e4ca9"
