[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "semver"
version = "1.1.1"
update_changelog_on_bump = true
branch = "master"
commit = "66ff895f3ae5f32b5724563f878e63d19533ad98"
